-- Update books table
ALTER TABLE IF EXISTS books 
ADD COLUMN IF NOT EXISTS isbn VARCHAR(13) UNIQUE,
ADD COLUMN IF NOT EXISTS author VARCHAR(255),
ADD COLUMN IF NOT EXISTS published_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS publisher VARCHAR(255),
ADD COLUMN IF NOT EXISTS language VARCHAR(50),
ADD COLUMN IF NOT EXISTS page_count INTEGER;