# Stage 1 - Build
FROM node:20-alpine AS builder

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=4096" \
    NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npx update-browserslist-db@latest && \
    npm run build